branches:
  - name: main
    protection:
      required_linear_history: true
      allow_force_pushes: false
      required_pull_request_reviews:
        # required_approving_review_count: 1
      required_status_checks:
        strict: true
        contexts: 
          - 'Production Branch Check'
          - 'Production Build'
          - 'Production Deploy'

  - name: staging
    protection:
      required_linear_history: true
      allow_force_pushes: false
      required_pull_request_reviews:
        # required_approving_review_count: 1
      required_status_checks:
        strict: true
        contexts: 
          - 'Staging Branch Check'
          - 'Staging Build'
          - 'Staging Deploy'

  - name: dev
    protection:
      required_linear_history: true
      allow_force_pushes: false
      required_status_checks:
        strict: true
        contexts: 
          - 'Development Build'
          - 'Development Deploy' 