FROM --platform=linux/amd64 node:lts as dependencies
WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn install

FROM --platform=linux/amd64 node:lts as builder

WORKDIR /app

ARG NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL

ARG NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
ENV NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=$NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY

ARG NEXT_PUBLIC_ZAPSIGN_URL
ENV NEXT_PUBLIC_ZAPSIGN_URL=$NEXT_PUBLIC_ZAPSIGN_URL

ARG NEXT_PUBLIC_BRDID_URL
ENV NEXT_PUBLIC_BRDID_URL=$NEXT_PUBLIC_BRDID_URL

ARG NEXT_PUBLIC_ACTION_BRDID
ENV NEXT_PUBLIC_ACTION_BRDID=$NEXT_PUBLIC_ACTION_BRDID

ARG NEXT_PUBLIC_CNPJWS_TOKEN
ENV NEXT_PUBLIC_CNPJWS_TOKEN=$NEXT_PUBLIC_CNPJWS_TOKEN

ARG NEXT_PUBLIC_TTL
ENV NEXT_PUBLIC_TTL=$NEXT_PUBLIC_TTL

ARG NEXT_PUBLIC_PUSHER_PUB_KEY
ENV NEXT_PUBLIC_PUSHER_PUB_KEY=$NEXT_PUBLIC_PUSHER_PUB_KEY

ARG NEXT_PUBLIC_PUSHER_CLUSTER
ENV NEXT_PUBLIC_PUSHER_CLUSTER=$NEXT_PUBLIC_PUSHER_CLUSTER

ARG NEXT_PUBLIC_INTERCOM_APP_ID
ENV NEXT_PUBLIC_INTERCOM_APP_ID=$NEXT_PUBLIC_INTERCOM_APP_ID

ARG NEXT_PUBLIC_INTERCOM_SECRET_KEY
ENV NEXT_PUBLIC_INTERCOM_SECRET_KEY=$NEXT_PUBLIC_INTERCOM_SECRET_KEY

ARG NEXT_PUBLIC_NODE_ENV
ENV NEXT_PUBLIC_NODE_ENV=$NEXT_PUBLIC_NODE_ENV

COPY . .
COPY --from=dependencies /app/node_modules ./node_modules

RUN yarn build

FROM --platform=linux/amd64 node:lts as runner
WORKDIR /app


ENV NODE_ENV production

COPY --from=builder /app/next.config.js ./next.config.js
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json

EXPOSE 3000
CMD ["yarn", "start"]