import CNAE from "./../Utils/CNAE.json";

export interface CrmFieldInterface {
  category: string; //example: basic_information
  description?: string;
  categoryTitle: string; //example: Informações Básicas
  field: string; //example: company_name
  fieldType: string; //example: text
  fieldTitle: string; //example: Nome da Empresa
  active: boolean; //example: true
  mandatory?: boolean;
  options?: Array<{ name: string; value: string }>;
}


export const crmFields: CrmFieldInterface[] = [
  {
    category: "basic_information",
    categoryTitle: "Informações Básicas",
    field: "company_name",
    fieldType: "text",
    fieldTitle: "Razão Social",
    active: false,
    mandatory: false,
    description: "A razão social da empresa.",
  },
  {
    category: "basic_information",
    categoryTitle: "Informações Básicas",
    field: "trading_name",
    fieldType: "text",
    fieldTitle: "Nome Fantasia",
    active: false,
    mandatory: false,
    description: "O nome fantasia da empresa.",
  },
  {
    category: "basic_information",
    categoryTitle: "Informações Básicas",
    field: "cnpj",
    fieldType: "text",
    fieldTitle: "CNPJ",
    active: false,
    mandatory: false,
    description: "O CNPJ da empresa. Deve conter 14 dígitos.",
  },
  {
    category: "basic_information",
    categoryTitle: "Informações Básicas",
    field: "cpf",
    fieldType: "text",
    fieldTitle: "CPF",
    active: false,
    mandatory: false,
    description: "O CPF do contato pessoa física. Deve conter 11 dígitos.",
  },
  {
    category: "basic_information",
    categoryTitle: "Informações Básicas",
    field: "company_size",
    fieldType: "text",
    fieldTitle: "Tamanho da Empresa",
    active: false,
    mandatory: false,
    description: "O número de funcionários da empresa.",
  },
  {
    category: "basic_information",
    categoryTitle: "Informações Básicas",
    field: "industry_sector",
    fieldType: "text",
    fieldTitle: "Setor de Atuação",
    active: false,
    mandatory: false,
    description: "O setor de atuação da empresa.",
  },
  {
    category: "basic_information",
    categoryTitle: "Informações Básicas",
    field: "business_type",
    fieldType: "select",
    fieldTitle: "Tipo de Negócio",
    active: false,
    mandatory: false,
    description: "O tipo de negócio da empresa. Ex: B2B, B2C, B2G, etc.",
    options: [
      { name: "Selecione...", value: "" },
      { name: "B2B", value: "B2B" },
      { name: "B2C", value: "B2C" },
      { name: "B2G", value: "B2G" },
      { name: "B2B2C", value: "B2B2C" },
      { name: "B2B2G", value: "B2B2G" },
      { name: "B2C2G", value: "B2C2G" },
      { name: "B2B2C2G", value: "B2B2C2G" },
    ],
  },
  {
    category: "basic_information",
    categoryTitle: "Informações Básicas",
    field: "contact_reference",
    fieldType: "text",
    fieldTitle: "Referência de Contato",
    active: false,
    mandatory: false,
    description: "Referência de contato da empresa.",
  },
  {
    category: "basic_information",
    categoryTitle: "Informações Básicas",
    field: "website",
    fieldType: "text",
    fieldTitle: "Website",
    active: false,
    mandatory: false,
    description: "O website da empresa.",
  },
  {
    category: "basic_information",
    categoryTitle: "Informações Básicas",
    field: "founding_date",
    fieldType: "date",
    fieldTitle: "Data de Fundação",
    active: false,
    mandatory: false,
    description: "A data de fundação da empresa.",
  },
  {
    category: "basic_information",
    categoryTitle: "Informações Básicas",
    field: "state_registration",
    fieldType: "text",
    fieldTitle: "Inscrição Estadual",
    active: false,
    mandatory: false,
    description: "A inscrição estadual da empresa.",
  },
  {
    category: "contact",
    categoryTitle: "Contato",
    field: "contact_name",
    fieldType: "text",
    fieldTitle: "Nome do Contato",
    active: false,
    mandatory: false,
    description: "O nome do contato da empresa.",
  },
  {
    category: "contact",
    categoryTitle: "Contato",
    field: "position",
    fieldType: "text",
    fieldTitle: "Cargo",
    active: false,
    mandatory: false,
    description: "O cargo do contato da empresa.",
  },
  {
    category: "contact",
    categoryTitle: "Contato",
    field: "department",
    fieldType: "text",
    fieldTitle: "Departamento",
    active: false,
    mandatory: false,
    description: "O departamento do contato da empresa.",
  },
  {
    category: "contact",
    categoryTitle: "Contato",
    field: "commercial_phone",
    fieldType: "text",
    fieldTitle: "Telefone Comercial",
    active: false,
    mandatory: false,
    description: "O telefone comercial do contato da empresa.",
  },
  {
    category: "contact",
    categoryTitle: "Contato",
    field: "cellphone",
    fieldType: "text",
    fieldTitle: "Celular",
    active: false,
    mandatory: false,
    description: "O celular do contato da empresa.",
  },
  {
    category: "contact",
    categoryTitle: "Contato",
    field: "email",
    fieldType: "text",
    fieldTitle: "E-mail",
    active: false,
    mandatory: false,
    description: "O e-mail do contato da empresa.",
  },
  {
    category: "contact",
    categoryTitle: "Contato",
    field: "linkedin",
    fieldType: "text",
    fieldTitle: "LinkedIn",
    active: false,
    mandatory: false,
    description: "O LinkedIn do contato da empresa.",
  },
  {
    category: "address",
    categoryTitle: "Endereço",
    field: "commercial_address",
    fieldType: "text",
    fieldTitle: "Endereço Comercial",
    active: false,
    mandatory: false,
    description: "O endereço comercial da empresa.",
  },
  {
    category: "address",
    categoryTitle: "Endereço",
    field: "neighborhood",
    fieldType: "text",
    fieldTitle: "Bairro",
    active: false,
    mandatory: false,
    description: "O bairro da empresa.",
  },
  {
    category: "address",
    categoryTitle: "Endereço",
    field: "city",
    fieldType: "text",
    fieldTitle: "Cidade",
    active: false,
    mandatory: false,
    description: "A cidade da empresa.",
  },
  {
    category: "address",
    categoryTitle: "Endereço",
    field: "state",
    fieldType: "select",
    fieldTitle: "Estado",
    active: false,
    mandatory: false,
    description: "O estado da empresa.",
    options: [
      { name: "Selecione...", value: "" },
      { name: "AC", value: "AC" },
      { name: "AL", value: "AL" },
      { name: "AP", value: "AP" },
      { name: "AM", value: "AM" },
      { name: "BA", value: "BA" },
      { name: "CE", value: "CE" },
      { name: "DF", value: "DF" },
      { name: "ES", value: "ES" },
      { name: "GO", value: "GO" },
      { name: "MA", value: "MA" },
      { name: "MT", value: "MT" },
      { name: "MS", value: "MS" },
      { name: "MG", value: "MG" },
      { name: "PA", value: "PA" },
      { name: "PB", value: "PB" },
      { name: "PR", value: "PR" },
      { name: "PE", value: "PE" },
      { name: "PI", value: "PI" },
      { name: "RJ", value: "RJ" },
      { name: "RN", value: "RN" },
      { name: "RS", value: "RS" },
      { name: "RO", value: "RO" },
      { name: "RR", value: "RR" },
      { name: "SC", value: "SC" },
      { name: "SP", value: "SP" },
      { name: "SE", value: "SE" },
      { name: "TO", value: "TO" }
    ],
  },
  {
    category: "address",
    categoryTitle: "Endereço",
    field: "zip_code",
    fieldType: "text",
    fieldTitle: "CEP",
    active: false,
    mandatory: false,
    description: "O CEP da empresa.",
  },
  {
    category: "address",
    categoryTitle: "Endereço",
    field: "country",
    fieldType: "select",
    fieldTitle: "País",
    active: false,
    mandatory: false,
    description: "O país da empresa.",
    options: [
      { name: "Selecione...", value: "" },
      { name: "Brasil", value: "Brasil" },
      { name: "Afeganistão", value: "Afeganistão" },
      { name: "África do Sul", value: "África do Sul" },
      { name: "Albânia", value: "Albânia" },
      { name: "Alemanha", value: "Alemanha" },
      { name: "Andorra", value: "Andorra" },
      { name: "Angola", value: "Angola" },
      { name: "Antiga e Barbuda", value: "Antiga e Barbuda" },
      { name: "Arábia Saudita", value: "Arábia Saudita" },
      { name: "Argélia", value: "Argélia" },
      { name: "Argentina", value: "Argentina" },
      { name: "Armênia", value: "Armênia" },
      { name: "Austrália", value: "Austrália" },
      { name: "Áustria", value: "Áustria" },
      { name: "Azerbaijão", value: "Azerbaijão" },
      { name: "Bahamas", value: "Bahamas" },
      { name: "Bangladesh", value: "Bangladesh" },
      { name: "Barbados", value: "Barbados" },
      { name: "Barein", value: "Barein" },
      { name: "Bélgica", value: "Bélgica" },
      { name: "Belize", value: "Belize" },
      { name: "Benin", value: "Benin" },
      { name: "Bielorrússia", value: "Bielorrússia" },
      { name: "Bolívia", value: "Bolívia" },
      { name: "Bósnia e Herzegovina", value: "Bósnia e Herzegovina" },
      { name: "Botsuana", value: "Botsuana" },
      { name: "Brunei", value: "Brunei" },
      { name: "Bulgária", value: "Bulgária" },
      { name: "Burkina Faso", value: " Burkina Faso" },
      { name: "Burundi", value: "Burundi" },
      { name: "Butão", value: "Butão" },
      { name: "Cabo Verde", value: "Cabo Verde" },
      { name: "Camarões", value: "Camarões" },
      { name: "Camboja", value: "Camboja" },
      { name: "Canadá", value: "Canadá" },
      { name: "Catar", value: "Catar" },
      { name: "Cazaquistão", value: "Cazaquistão" },
      { name: "Chade", value: "Chade" },
      { name: "Chile", value: "Chile" },
      { name: "China", value: "China" },
      { name: "Chipre", value: "Chipre" },
      { name: "Colômbia", value: "Colômbia" },
      { name: "Comores", value: "Comores" },
      { name: "Congo", value: "Congo" },
      { name: "Coreia do Norte", value: "Coreia do Norte" },
      { name: "Coreia do Sul", value: "Coreia do Sul" },
      { name: "Costa do Marfim", value: "Costa do Marfim" },
      { name: "Costa Rica", value: "Costa Rica" },
      { name: "Croácia", value: "Croácia" },
      { name: "Cuba", value: "Cuba" },
      { name: "Dinamarca", value: "Dinamarca" },
      { name: "Djibuti", value: "Djibuti" },
      { name: "Dominica", value: "Dominica" },
      { name: "Egito", value: "Egito" },
      { name: "Emirados Árabes Unidos", value: "Emirados Árabes Unidos" },
      { name: "Equador", value: "Equador" },
      { name: "Eritreia", value: "Eritreia" },
      { name: "Eslováquia", value: "Eslováquia" },
      { name: "Eslovênia", value: "Eslovênia" },
      { name: "Espanha", value: "Espanha" },
      { name: "Estados Unidos", value: "Estados Unidos" },
      { name: "Estônia", value: "Estônia" },
      { name: "Etiópia", value: "Etiópia" },
      { name: "Fiji", value: "Fiji" },
      { name: "Filipinas", value: "Filipinas" },
      { name: "Finlândia", value: "Finlândia" },
      { name: "França", value: "França" },
      { name: "Gabão", value: "Gabão" },
      { name: "Gâmbia", value: "Gâmbia" },
      { name: "Gana", value: "Gana" },
      { name: "Geórgia", value: "Geórgia" },
      { name: "Granada", value: "Granada" },
      { name: "Grécia", value: "Grécia" },
      { name: "Guatemala", value: "Guatemala" },
      { name: "Guiana", value: "Guiana" },
      { name: "Guiné", value: "Guiné" },
      { name: "Guiné Equatorial", value: "Guiné Equatorial" },
      { name: "Guiné-Bissau", value: "Guiné-Bissau" },
      { name: "Haiti", value: "Haiti" },
      { name: "Holanda", value: "Holanda" },
      { name: "Honduras", value: "Honduras" },
      { name: "Hungria", value: "Hungria" },
      { name: "Iêmen", value: "Iêmen" },
      { name: "Ilhas Marshall", value: "Ilhas Marshall" },
      { name: "Ilhas Salomão", value: "Ilhas Salomão" },
      { name: "Índia", value: "Índia" },
      { name: "Indonésia", value: "Indonésia" },
      { name: "Irã", value: "Irã" },
      { name: "Iraque", value: "Iraque" },
      { name: "Irlanda", value: "Irlanda" },
      { name: "Islândia", value: "Islândia" }
    ],
  }
];
