apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.config.name }}-credentials
  namespace: {{ .Values.namespace }}
  labels:
    name: {{ include "charts-frontend-platform.fullname" . }}
    {{- include "charts-frontend-platform.labels" . | nindent 4 }}
type: Opaque
data:
  next-public-stripe-publishable-key: {{ .Values.config.nextPublicStripePublishableKey | b64enc | quote }}
  sentry-dsn: {{ .Values.config.sentryDns | b64enc | quote }}
  next-public-zapsign-url: {{ .Values.config.nextPublicZapSignUrl | b64enc | quote }}
  sentry-auth-token: {{ .Values.config.sentryAuthToken | b64enc | quote }}
  next-public-brdid-url: {{ .Values.config.nextPublicBrdidUrl | b64enc | quote }}
  next-public-cnpjws-token: {{ .Values.config.nextPublicCnpjwsToken | b64enc | quote }}
  next-public-stripe-trimestral-price-id: {{ .Values.config.nextPublicStripeTrimestralPriceId | b64enc | quote }}
  next-public-stripe-semestral-price-id: {{ .Values.config.nextPublicStripeSemestralPriceId | b64enc | quote }}
  next-public-stripe-anual-price-id: {{ .Values.config.nextPublicStripeAnualPriceId | b64enc | quote }}
  next-public-ttl: {{ .Values.config.nextPublicTtl | b64enc | quote }}
  next-public-pusher-cluster: {{ .Values.config.nextPublicPusherCluster | b64enc | quote }}
  next-public-intercom-app-id: {{ .Values.config.nextPublicIntercomAppId | b64enc | quote }}
  next-public-intercom-secret-key: {{ .Values.config.nextPublicIntercomSecretKey | b64enc | quote }}
  next-public-api-url: {{ .Values.config.nextPublicapiUrl | b64enc | quote }}
  next-public-pusher-pub-key: {{ .Values.config.nextPublicpusherPubKey | b64enc | quote }}
  next-public-broadcaster-url: {{ .Values.config.nextPublicBroadcasterUrl | b64enc | quote }}