apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.config.name }}-credentials
  namespace: {{ .Values.namespace }}
  labels:
    name: {{ include "charts-frontend-site.fullname" . }}
    {{- include "charts-frontend-site.labels" . | nindent 4 }}
type: Opaque
data:
  next-public-api-url: {{ .Values.config.nextPublicapiUrl | b64enc | quote }}
  next-public-frontend-platform: {{ .Values.config.nextPublicFrontendPlatform | b64enc | quote }} 