apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "charts-communication-service.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    name: {{ include "charts-communication-service.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "charts-communication-service.fullname" . }}
                port:
                  number: 80
