apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-site-staging
  namespace: frontend-site
  labels:
    name: {{ include "charts-frontend-site.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
    - host: frontend.staging.wearebren.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-site-staging
                port:
                  number: 80
