apiVersion: v1
kind: Service
metadata:
  name: {{ include "charts-frontend-platform.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    name: {{ include "charts-frontend-platform.fullname" . }}
    {{- include "charts-frontend-platform.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    {{- include "charts-frontend-platform.selectorLabels" . | nindent 4 }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
