apiVersion: v1
kind: Service
metadata:
  name: {{ include "charts-frontend-platform.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    name: {{ include "charts-frontend-platform.fullname" . }}
    {{- include "charts-frontend-platform.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "charts-frontend-platform.selectorLabels" . | nindent 4 }}
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 3000
  type: ClusterIP
