{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "charts-frontend-site.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    name: {{ include "charts-frontend-site.fullname" . }}
    {{- include "charts-frontend-site.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
