apiVersion: v1
kind: Service
metadata:
  name: {{ include "charts-frontend-site.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    name: {{ include "charts-frontend-site.fullname" . }}
    {{- include "charts-frontend-site.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "charts-frontend-site.selectorLabels" . | nindent 4 }}
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 3000
  - name: https
    protocol: TCP
    port: 443
    targetPort: 3000
  type: ClusterIP

